// <auto-generated />
using System;
using DiaryService.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiaryService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523145607_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiaryService.Domain.DiaryService.Domain.Entities.ExerciseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("CompletedExercise")
                        .HasColumnType("text")
                        .HasColumnName("completed_exercise");

                    b.Property<DateTime?>("CompletedExerciseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_exercise_date");

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise");

                    b.Property<DateTime>("ExerciseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exercise_date");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("exercise", (string)null);
                });

            modelBuilder.Entity("DiaryService.Domain.DiaryService.Domain.Entities.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("diary_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<DateTime>("GradeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grade_date");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("diary", (string)null);
                });

            modelBuilder.Entity("DiaryService.Domain.DiaryService.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("middlename");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("firstname");

                    b.HasKey("Id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("DiaryService.Domain.DiaryService.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("middlename");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("firstname");

                    b.HasKey("Id");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("DiaryService.Domain.DiaryService.Domain.Entities.ExerciseRecord", b =>
                {
                    b.HasOne("DiaryService.Domain.DiaryService.Domain.Entities.Student", "Student")
                        .WithMany("Exercises")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaryService.Domain.DiaryService.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Exercises")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DiaryService.Domain.DiaryService.Domain.Entities.Journal", b =>
                {
                    b.HasOne("DiaryService.Domain.DiaryService.Domain.Entities.ExerciseRecord", "ExerciseRecord")
                        .WithMany("Journals")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaryService.Domain.DiaryService.Domain.Entities.Student", "Student")
                        .WithMany("Journals")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaryService.Domain.DiaryService.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Journals")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExerciseRecord");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DiaryService.Domain.DiaryService.Domain.Entities.ExerciseRecord", b =>
                {
                    b.Navigation("Journals");
                });

            modelBuilder.Entity("DiaryService.Domain.DiaryService.Domain.Entities.Student", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Journals");
                });

            modelBuilder.Entity("DiaryService.Domain.DiaryService.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Journals");
                });
#pragma warning restore 612, 618
        }
    }
}
